### ISSUE TITLE
Header changes

### ISSUE THREAD

**Issue by Stellyna** [FHCN/ifoundmydoctor#33]
Please increase the font size on "The online presence of Florida Health Care News" by at least 2 pts.

**Comment by Stellyna** [comment]
Also remove Social media icons

![screen shot 2018-10-02 at 10 31 33 am](https://user-images.githubusercontent.com/30607569/46355758-6d0aff80-c62f-11e8-90de-3f09949d1271.jpg)

**Comment by Stellyna** [comment]
Let's try 4 pts.

**Comment by johnsonw** [comment]
Here's what it looks like after the update:

![image](https://user-images.githubusercontent.com/1100657/47405080-e6bd7700-d71d-11e8-9c37-20948056e951.png)
